### ISSUE TITLE
Disable endpoints / views when S8 starts

### ISSUE THREAD

**Issue by thijskuilman** [yukka-nl/game-of-thrones-pool#65]
**Routes**
- [x] Route::post('/prediction', 'PredictionController@store');
- [x] Route::get('/prediction/create', 'PredictionController@create')->name('make-prediction');
- [x] Route::get('/prediction/edit', 'PredictionController@edit');
- [x] Route::put('/prediction', 'PredictionController@update');
- [x] Route::post('/predictions/house', 'HouseController@storePrediction');
- [x] Route::post('/houses/join', 'HouseController@join');
- [x] Route::get('/predictions/house', 'HouseController@predictions');

**Views**
- [x] Create prediction (also remove the button on the homepage)
- [x] Create house prediction (also remove the button on the homepage)
- [x] Remove 'Edit your prediction' on user prediction page and homepage (below 'View your prediction')
- [x] Remove CTA for joining a house

**Misc**
- [x] Remove season countdown

**Comment by ruudz** [comment]
Also removed registration.
